# rolearn      = "arn:aws:iam::322266404742:role/dev-terraform-create-role"
  rolearn      = "arn:aws:iam::334870576011:role/eks-client-ssm-role"
# env_name     = "prod"
# cluster_name = "prod-dominion-cluster"
# key_name     = "eks-client-key"